version: 2.1

jobs:
  fetch_stars:
    docker:
      - image: circleci/node

    steps:
      - checkout

      - run:
          working_directory: src/ts
          command: npm install

      - run:
          working_directory: src/ts
          command: npm run build

      - run:
          command: env

      - run:
          working_directory: src/ts
          command: node fetch_stars.js  -o mlflow -r mlflow -c stars.csv

      - persist_to_workspace:
          root: .
          paths:
            - src/ts/stars.csv

  plot_stars:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - run:
          command: pip install -r src/python/requirements.txt

      - attach_workspace:
          at: .

      - run:
          command: python src/python/plot_stars.py -c src/ts/stars.csv

      - store_artifacts:
          path: /src/ts/stars.html

workflows:
  main:
    jobs:
      - fetch_stars
      - plot_stars:
          requires:
            - fetch_stars
