version: 2.1

jobs:
  create_plot:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Create the star-count plot
          command: python fetch_stars.py -o mlflow -r mlflow -f stars.html

      - store_artifacts:
          path: ./stars.html

workflows:
  main:
    jobs:
      - create_plot
